name: CI
env:
  DEBUG: napi:*
  APP_NAME: smart-archive-rar
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
  pull_request: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install dependencies
        run: npm ci
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --workspace
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: npx napi build --platform --release --target x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
            build: npx napi build --platform --release --target aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: npx napi build --platform --release --target x86_64-pc-windows-msvc
          - host: windows-latest
            target: i686-pc-windows-msvc
            build: npx napi build --platform --release --target i686-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: npx napi build --platform --release --target aarch64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npx napi build --platform --release --target x86_64-unknown-linux-gnu --use-napi-cross
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: npx napi build --platform --release --target x86_64-unknown-linux-musl -x
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: npx napi build --platform --release --target aarch64-unknown-linux-gnu --use-napi-cross
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: npx napi build --platform --release --target aarch64-unknown-linux-musl -x
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: npx napi build --platform --release --target armv7-unknown-linux-gnueabihf --use-napi-cross
    name: build - ${{ matrix.settings.target }} - node@22
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.napi-rs
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: ${{ matrix.settings.build }}
      - name: Test on host
        run: npm test
        if: ${{ !contains(matrix.settings.target, 'unknown-linux-musl') && !contains(matrix.settings.target, 'unknown-linux-gnu') }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.settings.target }}
          path: |
            *.node
            index.js
            index.d.ts
